---

include:
  - project: veepee/vptech/sre/iac/ci-cd/markdown-lint
    ref: 1.3.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/semantic-release
    ref: 3.6.0
    file: gitlab-ci.yml
  - project: veepee/vptech/sre/iac/ci-cd/shellcheck
    ref: 1.1.0
    file: gitlab-ci.yml

.template: &build
  stage: build
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - apk update && apk add bash curl
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - docker login -u "$DOCKER_PUBLIC_REGISTRY_USERNAME" -p "$DOCKER_PUBLIC_REGISTRY_PASSWORD"
    - docker load -i image/alpine-v3.10.tar
    - docker load -i image/alpine-v3.11.tar
    - docker load -i image/alpine-v3.12.tar
    - docker load -i image/alpine-v3.13.tar
  only:
    - master
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - deploy
  - release

v3.10:
  <<: *build
  script:
    - ./build.sh -d 3.10
    - mkdir image
    - docker save alpine:3.10 > image/alpine-v3.10.tar

v3.11:
  <<: *build
  script:
    - ./build.sh -d 3.11
    - mkdir image
    - docker save alpine:3.11 > image/alpine-v3.11.tar

v3.12:
  <<: *build
  script:
    - ./build.sh -d 3.12
    - mkdir image
    - docker save alpine:3.12 > image/alpine-v3.12.tar

v3.13:
  <<: *build
  script:
    - ./build.sh -d 3.13
    - mkdir image
    - docker save alpine:3.13 > image/alpine-v3.13.tar

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag alpine:3.10 vptech/alpine:3.10
    - docker tag alpine:3.11 vptech/alpine:3.11
    - docker tag alpine:3.12 vptech/alpine:3.12
    - docker tag alpine:3.13 vptech/alpine:3.13
    - docker tag alpine:3.13 vptech/alpine:latest
    - docker push --all-tags vptech/alpine
# EOF
