---

include:
  - project: veepee/vptech/ci-cd/markdown-lint
    ref: 1-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/semantic-release
    ref: 2-latest
    file: gitlab-ci.yml
  - project: veepee/vptech/ci-cd/shellcheck
    ref: 2-latest
    file: gitlab-ci.yml

.template: &build
  stage: build
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - apk update && apk add bash curl
  artifacts:
    expire_in: 1 day
    paths:
      - image
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  stage: deploy
  image: docker.registry.vptech.eu/docker:latest
  before_script:
    - docker login -u "$DOCKER_PUBLIC_REGISTRY_USERNAME" -p "$DOCKER_PUBLIC_REGISTRY_PASSWORD"
    - docker load -i image/alpine-v3.14.tar
    - docker load -i image/alpine-v3.15.tar
    - docker load -i image/alpine-v3.16.tar
    - docker load -i image/alpine-v3.18.tar
    - docker load -i image/alpine-v3.19.tar
    - docker load -i image/alpine-v3.20.tar
    - docker load -i image/alpine-v3.22.tar
  only:
    - main
    - master
  services:
    - name: docker.registry.vptech.eu/docker:dind
      alias: docker
  tags:
    - dind
  variables:
    DOCKER_DRIVER: overlay

stages:
  - lint
  - build
  - deploy
  - release

build:3.14:
  <<: *build
  script:
    - ./build.sh -d 3.14
    - mkdir image
    - docker save alpine:3.14 > image/alpine-v3.14.tar

build:3.15:
  <<: *build
  script:
    - ./build.sh -d 3.15
    - mkdir image
    - docker save alpine:3.15 > image/alpine-v3.15.tar

build:3.16:
  <<: *build
  script:
    - ./build.sh -d 3.16
    - mkdir image
    - docker save alpine:3.16 > image/alpine-v3.16.tar

build:3.18:
  <<: *build
  script:
    - ./build.sh -d 3.18
    - mkdir image
    - docker save alpine:3.18 > image/alpine-v3.18.tar

build:3.19:
  <<: *build
  script:
    - ./build.sh -d 3.19
    - mkdir image
    - docker save alpine:3.19 > image/alpine-v3.19.tar

build:3.20:
  <<: *build
  script:
    - ./build.sh -d 3.20
    - mkdir image
    - docker save alpine:3.20 > image/alpine-v3.20.tar

build:3.22:
  <<: *build
  script:
    - ./build.sh -d 3.22
    - mkdir image
    - docker save alpine:3.22 > image/alpine-v3.22.tar

# https://hub.docker.com/u/vptech/
vptech:
  <<: *deploy
  script:
    - docker tag alpine:3.14 vptech/alpine:3.14
    - docker tag alpine:3.15 vptech/alpine:3.15
    - docker tag alpine:3.16 vptech/alpine:3.16
    - docker tag alpine:3.18 vptech/alpine:3.18
    - docker tag alpine:3.19 vptech/alpine:3.19
    - docker tag alpine:3.20 vptech/alpine:3.20
    - docker tag alpine:3.22 vptech/alpine:3.22
    - docker tag alpine:3.22 vptech/alpine:latest
    - docker push --all-tags vptech/alpine
# EOF
